name 'supervisord'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures supervisord'
long_description 'Installs/Configures supervisord'
version '0.1.0'
